/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowRouteImport } from './routes/workflow'
import { Route as VendorRouteImport } from './routes/vendor'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as MarketingToolRouteImport } from './routes/marketing-tool'
import { Route as BulkUploadStudioRouteImport } from './routes/bulk-upload-studio'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as ApiRemoveBgRouteImport } from './routes/api/remove-bg'
import { Route as ApiDecorProjectRouteImport } from './routes/api/decor-project'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAiImageRouteImport } from './routes/api/ai-image'

const WorkflowRoute = WorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorRoute = VendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingToolRoute = MarketingToolRouteImport.update({
  id: '/marketing-tool',
  path: '/marketing-tool',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkUploadStudioRoute = BulkUploadStudioRouteImport.update({
  id: '/bulk-upload-studio',
  path: '/bulk-upload-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemoveBgRoute = ApiRemoveBgRouteImport.update({
  id: '/api/remove-bg',
  path: '/api/remove-bg',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDecorProjectRoute = ApiDecorProjectRouteImport.update({
  id: '/api/decor-project',
  path: '/api/decor-project',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiImageRoute = ApiAiImageRouteImport.update({
  id: '/api/ai-image',
  path: '/api/ai-image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assistant': typeof AssistantRoute
  '/bulk-upload-studio': typeof BulkUploadStudioRoute
  '/marketing-tool': typeof MarketingToolRoute
  '/marketplace': typeof MarketplaceRoute
  '/simulator': typeof SimulatorRoute
  '/vendor': typeof VendorRoute
  '/workflow': typeof WorkflowRoute
  '/api/ai-image': typeof ApiAiImageRoute
  '/api/chat': typeof ApiChatRoute
  '/api/decor-project': typeof ApiDecorProjectRoute
  '/api/remove-bg': typeof ApiRemoveBgRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assistant': typeof AssistantRoute
  '/bulk-upload-studio': typeof BulkUploadStudioRoute
  '/marketing-tool': typeof MarketingToolRoute
  '/marketplace': typeof MarketplaceRoute
  '/simulator': typeof SimulatorRoute
  '/vendor': typeof VendorRoute
  '/workflow': typeof WorkflowRoute
  '/api/ai-image': typeof ApiAiImageRoute
  '/api/chat': typeof ApiChatRoute
  '/api/decor-project': typeof ApiDecorProjectRoute
  '/api/remove-bg': typeof ApiRemoveBgRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assistant': typeof AssistantRoute
  '/bulk-upload-studio': typeof BulkUploadStudioRoute
  '/marketing-tool': typeof MarketingToolRoute
  '/marketplace': typeof MarketplaceRoute
  '/simulator': typeof SimulatorRoute
  '/vendor': typeof VendorRoute
  '/workflow': typeof WorkflowRoute
  '/api/ai-image': typeof ApiAiImageRoute
  '/api/chat': typeof ApiChatRoute
  '/api/decor-project': typeof ApiDecorProjectRoute
  '/api/remove-bg': typeof ApiRemoveBgRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/assistant'
    | '/bulk-upload-studio'
    | '/marketing-tool'
    | '/marketplace'
    | '/simulator'
    | '/vendor'
    | '/workflow'
    | '/api/ai-image'
    | '/api/chat'
    | '/api/decor-project'
    | '/api/remove-bg'
    | '/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/assistant'
    | '/bulk-upload-studio'
    | '/marketing-tool'
    | '/marketplace'
    | '/simulator'
    | '/vendor'
    | '/workflow'
    | '/api/ai-image'
    | '/api/chat'
    | '/api/decor-project'
    | '/api/remove-bg'
    | '/product/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/assistant'
    | '/bulk-upload-studio'
    | '/marketing-tool'
    | '/marketplace'
    | '/simulator'
    | '/vendor'
    | '/workflow'
    | '/api/ai-image'
    | '/api/chat'
    | '/api/decor-project'
    | '/api/remove-bg'
    | '/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AssistantRoute: typeof AssistantRoute
  BulkUploadStudioRoute: typeof BulkUploadStudioRoute
  MarketingToolRoute: typeof MarketingToolRoute
  MarketplaceRoute: typeof MarketplaceRoute
  SimulatorRoute: typeof SimulatorRoute
  VendorRoute: typeof VendorRoute
  WorkflowRoute: typeof WorkflowRoute
  ApiAiImageRoute: typeof ApiAiImageRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiDecorProjectRoute: typeof ApiDecorProjectRoute
  ApiRemoveBgRoute: typeof ApiRemoveBgRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflow': {
      id: '/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof WorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor': {
      id: '/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof VendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing-tool': {
      id: '/marketing-tool'
      path: '/marketing-tool'
      fullPath: '/marketing-tool'
      preLoaderRoute: typeof MarketingToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk-upload-studio': {
      id: '/bulk-upload-studio'
      path: '/bulk-upload-studio'
      fullPath: '/bulk-upload-studio'
      preLoaderRoute: typeof BulkUploadStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/remove-bg': {
      id: '/api/remove-bg'
      path: '/api/remove-bg'
      fullPath: '/api/remove-bg'
      preLoaderRoute: typeof ApiRemoveBgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/decor-project': {
      id: '/api/decor-project'
      path: '/api/decor-project'
      fullPath: '/api/decor-project'
      preLoaderRoute: typeof ApiDecorProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-image': {
      id: '/api/ai-image'
      path: '/api/ai-image'
      fullPath: '/api/ai-image'
      preLoaderRoute: typeof ApiAiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AssistantRoute: AssistantRoute,
  BulkUploadStudioRoute: BulkUploadStudioRoute,
  MarketingToolRoute: MarketingToolRoute,
  MarketplaceRoute: MarketplaceRoute,
  SimulatorRoute: SimulatorRoute,
  VendorRoute: VendorRoute,
  WorkflowRoute: WorkflowRoute,
  ApiAiImageRoute: ApiAiImageRoute,
  ApiChatRoute: ApiChatRoute,
  ApiDecorProjectRoute: ApiDecorProjectRoute,
  ApiRemoveBgRoute: ApiRemoveBgRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
