/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowRouteImport } from './routes/workflow'
import { Route as TryonRouteImport } from './routes/tryon'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as MarketingToolRouteImport } from './routes/marketing-tool'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as ApiTryonRouteImport } from './routes/api/tryon'
import { Route as ApiRemoveBgRouteImport } from './routes/api/remove-bg'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const WorkflowRoute = WorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const TryonRoute = TryonRouteImport.update({
  id: '/tryon',
  path: '/tryon',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingToolRoute = MarketingToolRouteImport.update({
  id: '/marketing-tool',
  path: '/marketing-tool',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTryonRoute = ApiTryonRouteImport.update({
  id: '/api/tryon',
  path: '/api/tryon',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemoveBgRoute = ApiRemoveBgRouteImport.update({
  id: '/api/remove-bg',
  path: '/api/remove-bg',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/marketing-tool': typeof MarketingToolRoute
  '/marketplace': typeof MarketplaceRoute
  '/simulator': typeof SimulatorRoute
  '/tryon': typeof TryonRoute
  '/workflow': typeof WorkflowRoute
  '/api/chat': typeof ApiChatRoute
  '/api/remove-bg': typeof ApiRemoveBgRoute
  '/api/tryon': typeof ApiTryonRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/marketing-tool': typeof MarketingToolRoute
  '/marketplace': typeof MarketplaceRoute
  '/simulator': typeof SimulatorRoute
  '/tryon': typeof TryonRoute
  '/workflow': typeof WorkflowRoute
  '/api/chat': typeof ApiChatRoute
  '/api/remove-bg': typeof ApiRemoveBgRoute
  '/api/tryon': typeof ApiTryonRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/marketing-tool': typeof MarketingToolRoute
  '/marketplace': typeof MarketplaceRoute
  '/simulator': typeof SimulatorRoute
  '/tryon': typeof TryonRoute
  '/workflow': typeof WorkflowRoute
  '/api/chat': typeof ApiChatRoute
  '/api/remove-bg': typeof ApiRemoveBgRoute
  '/api/tryon': typeof ApiTryonRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/marketing-tool'
    | '/marketplace'
    | '/simulator'
    | '/tryon'
    | '/workflow'
    | '/api/chat'
    | '/api/remove-bg'
    | '/api/tryon'
    | '/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/marketing-tool'
    | '/marketplace'
    | '/simulator'
    | '/tryon'
    | '/workflow'
    | '/api/chat'
    | '/api/remove-bg'
    | '/api/tryon'
    | '/product/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/marketing-tool'
    | '/marketplace'
    | '/simulator'
    | '/tryon'
    | '/workflow'
    | '/api/chat'
    | '/api/remove-bg'
    | '/api/tryon'
    | '/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  MarketingToolRoute: typeof MarketingToolRoute
  MarketplaceRoute: typeof MarketplaceRoute
  SimulatorRoute: typeof SimulatorRoute
  TryonRoute: typeof TryonRoute
  WorkflowRoute: typeof WorkflowRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiRemoveBgRoute: typeof ApiRemoveBgRoute
  ApiTryonRoute: typeof ApiTryonRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflow': {
      id: '/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof WorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tryon': {
      id: '/tryon'
      path: '/tryon'
      fullPath: '/tryon'
      preLoaderRoute: typeof TryonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing-tool': {
      id: '/marketing-tool'
      path: '/marketing-tool'
      fullPath: '/marketing-tool'
      preLoaderRoute: typeof MarketingToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tryon': {
      id: '/api/tryon'
      path: '/api/tryon'
      fullPath: '/api/tryon'
      preLoaderRoute: typeof ApiTryonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/remove-bg': {
      id: '/api/remove-bg'
      path: '/api/remove-bg'
      fullPath: '/api/remove-bg'
      preLoaderRoute: typeof ApiRemoveBgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  MarketingToolRoute: MarketingToolRoute,
  MarketplaceRoute: MarketplaceRoute,
  SimulatorRoute: SimulatorRoute,
  TryonRoute: TryonRoute,
  WorkflowRoute: WorkflowRoute,
  ApiChatRoute: ApiChatRoute,
  ApiRemoveBgRoute: ApiRemoveBgRoute,
  ApiTryonRoute: ApiTryonRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
