/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MarketingToolRouteImport } from './routes/marketing-tool'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as BulkUploadStudioRouteImport } from './routes/bulk-upload-studio'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRemoveBgRouteImport } from './routes/api/remove-bg'
import { Route as ApiDecorProjectRouteImport } from './routes/api/decor-project'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAiImageRouteImport } from './routes/api/ai-image'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingToolRoute = MarketingToolRouteImport.update({
  id: '/marketing-tool',
  path: '/marketing-tool',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkUploadStudioRoute = BulkUploadStudioRouteImport.update({
  id: '/bulk-upload-studio',
  path: '/bulk-upload-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemoveBgRoute = ApiRemoveBgRouteImport.update({
  id: '/api/remove-bg',
  path: '/api/remove-bg',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDecorProjectRoute = ApiDecorProjectRouteImport.update({
  id: '/api/decor-project',
  path: '/api/decor-project',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiImageRoute = ApiAiImageRouteImport.update({
  id: '/api/ai-image',
  path: '/api/ai-image',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assistant': typeof AssistantRoute
  '/bulk-upload-studio': typeof BulkUploadStudioRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/marketing-tool': typeof MarketingToolRoute
  '/mcp': typeof McpRoute
  '/simulator': typeof SimulatorRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/ai-image': typeof ApiAiImageRoute
  '/api/chat': typeof ApiChatRoute
  '/api/decor-project': typeof ApiDecorProjectRoute
  '/api/remove-bg': typeof ApiRemoveBgRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assistant': typeof AssistantRoute
  '/bulk-upload-studio': typeof BulkUploadStudioRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/marketing-tool': typeof MarketingToolRoute
  '/mcp': typeof McpRoute
  '/simulator': typeof SimulatorRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/ai-image': typeof ApiAiImageRoute
  '/api/chat': typeof ApiChatRoute
  '/api/decor-project': typeof ApiDecorProjectRoute
  '/api/remove-bg': typeof ApiRemoveBgRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assistant': typeof AssistantRoute
  '/bulk-upload-studio': typeof BulkUploadStudioRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/marketing-tool': typeof MarketingToolRoute
  '/mcp': typeof McpRoute
  '/simulator': typeof SimulatorRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/ai-image': typeof ApiAiImageRoute
  '/api/chat': typeof ApiChatRoute
  '/api/decor-project': typeof ApiDecorProjectRoute
  '/api/remove-bg': typeof ApiRemoveBgRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/assistant'
    | '/bulk-upload-studio'
    | '/gallery'
    | '/login'
    | '/marketing-tool'
    | '/mcp'
    | '/simulator'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/ai-image'
    | '/api/chat'
    | '/api/decor-project'
    | '/api/remove-bg'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/assistant'
    | '/bulk-upload-studio'
    | '/gallery'
    | '/login'
    | '/marketing-tool'
    | '/mcp'
    | '/simulator'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/ai-image'
    | '/api/chat'
    | '/api/decor-project'
    | '/api/remove-bg'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/assistant'
    | '/bulk-upload-studio'
    | '/gallery'
    | '/login'
    | '/marketing-tool'
    | '/mcp'
    | '/simulator'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/ai-image'
    | '/api/chat'
    | '/api/decor-project'
    | '/api/remove-bg'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AssistantRoute: typeof AssistantRoute
  BulkUploadStudioRoute: typeof BulkUploadStudioRoute
  GalleryRoute: typeof GalleryRoute
  LoginRoute: typeof LoginRoute
  MarketingToolRoute: typeof MarketingToolRoute
  McpRoute: typeof McpRoute
  SimulatorRoute: typeof SimulatorRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiAiImageRoute: typeof ApiAiImageRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiDecorProjectRoute: typeof ApiDecorProjectRoute
  ApiRemoveBgRoute: typeof ApiRemoveBgRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing-tool': {
      id: '/marketing-tool'
      path: '/marketing-tool'
      fullPath: '/marketing-tool'
      preLoaderRoute: typeof MarketingToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk-upload-studio': {
      id: '/bulk-upload-studio'
      path: '/bulk-upload-studio'
      fullPath: '/bulk-upload-studio'
      preLoaderRoute: typeof BulkUploadStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/remove-bg': {
      id: '/api/remove-bg'
      path: '/api/remove-bg'
      fullPath: '/api/remove-bg'
      preLoaderRoute: typeof ApiRemoveBgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/decor-project': {
      id: '/api/decor-project'
      path: '/api/decor-project'
      fullPath: '/api/decor-project'
      preLoaderRoute: typeof ApiDecorProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-image': {
      id: '/api/ai-image'
      path: '/api/ai-image'
      fullPath: '/api/ai-image'
      preLoaderRoute: typeof ApiAiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AssistantRoute: AssistantRoute,
  BulkUploadStudioRoute: BulkUploadStudioRoute,
  GalleryRoute: GalleryRoute,
  LoginRoute: LoginRoute,
  MarketingToolRoute: MarketingToolRoute,
  McpRoute: McpRoute,
  SimulatorRoute: SimulatorRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiAiImageRoute: ApiAiImageRoute,
  ApiChatRoute: ApiChatRoute,
  ApiDecorProjectRoute: ApiDecorProjectRoute,
  ApiRemoveBgRoute: ApiRemoveBgRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
